# Generated by Django 4.2.4 on 2023-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('products', models.ManyToManyField(related_name='orders', to='Todo.productlist')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
